name: 🧪 WebdriverIO Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      run: docker --version
   
    - name: Build Docker image
      run: |
        docker build \
          -t wdio-tests:ci .

    - name: Run WDIO tests inside container
      run: |
          docker run --rm 
          -e API_USERNAME=${{ secrets.API_USERNAME }} \
          -e API_PASSWORD: ${{ secrets.API_PASSWORD }} \
          -e API_URL: ${{ secrets.API_URL }}\
          -e API_INVUSERNAME: ${{ secrets.API_INVUSERNAME }} \
          -e API_INVPASSWORD: ${{ secrets.API_INVPASSWORD }} \
          -e API_INVURL: ${{ secrets.API_INVURL }} \
          wdio-tests:ci 

      
