name: 🧪 WebdriverIO Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      run: docker --version

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Set environment variables
      run: |
          echo "API_USERNAME=${{ secrets.API_USERNAME }}" >> $GITHUB_ENV
          echo "API_PASSWORD=${{ secrets.API_PASSWORD }}" >> $GITHUB_ENV
          echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
          echo "API_INVUSERNAME=${{ secrets.API_INVUSERNAME }}" >> $GITHUB_ENV
          echo "API_INVPASSWORD=${{ secrets.API_INVPASSWORD }}" >> $GITHUB_ENV
          echo "API_INVURL=${{ secrets.API_INVURL }}" >> $GITHUB_ENV

    - name: Build and run WDIO tests
      run: |
          docker-compose -f restfulbookerapi/docker-compose.yml up --build --abort-on-container-exit

    - name: Shutdown Docker Compose
      if: always()
      run: docker-compose -f restfulbookerapi/docker-compose.yml down

    

   
  
           

      
